### ISSUE TITLE
Áreas de Atuação - Back-end

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-webapp#106]
1. Inserir texto sobre a área Back-end na SouJunior
2. Apresentar Head da área com foto
3. Foto da equipe

**Definição**

**Como** usuário 
**Gostaria** de acessar o site 
**Para** conhecer mais sobre a Área de Back-end juntamente com a entrevista do Head.

**Descrição:**

Este documento tem como objetivo, apresentar aos usuários como atua Back-end

**Protótipo**

https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/SITE---Sou-Junior?page-id=3609%3A96&type=design&node-id=3811-4960&viewport=1075%2C337%2C0.11&t=SHzlf8uK3KZmBmok-1&scaling=min-zoom&mode=design

![Image](https://user-images.githubusercontent.com/115566254/224721773-ce7a4f2e-90d9-458e-bed4-70b731df6267.png)

**Critérios de aceite**

**1-** Para acesso a "**Área de Atuação**" o usuário deverá acessar o site da SouJunior.

![Image](https://user-images.githubusercontent.com/115566254/224723952-f364efc0-b353-4c95-b3eb-3b58e1966d0c.png)

**2-** Após acessar o site da SouJunior, o usuário deverá descer a barra de rolagem até a "**Área de atuação**" e selecionar a
opção "Back-end"

![Image](https://user-images.githubusercontent.com/115566254/222827438-edc1d15d-d7c2-418d-adea-700d1e8b3e6d.png)

**3-** Após o usuário selecionar a opção "**Back-end**" o usuário visualizará duas seções uma contendo a apresentação sobre a área de Back-end a segunda sendo a entrevista com a Head da Área de Back-end da SouJunior, **Wanderson Santos**.

**4-** Antes da entrevista, deverá constar a foto Head da Área de Back-end - **Wanderson Santos**  e suas redes sociais.

- **LinkedIn:** https://www.linkedin.com/in/wandersongsantos/
- **Discord:**: 427653385123135490

**5-** No final da entrevista deverá constar a foto da equipe de Back-end da SouJunior, junto com o LinkedIn e Discord.

**6-** Ao clicar no botão do Linkedin ou do Discord, o usuário deverá ser informado de que ele será direcionado para uma nova página em outra aba, para que o Usuário possa continuar navegando no Site caso desejado.

**7-** Para o usuário retornar a página inicial do site SouJunior, deverá selecionar o botão de retroceder da página.

![Image](https://user-images.githubusercontent.com/115566254/224724910-ce03922a-4de5-42d1-9deb-f12b149ab130.png)

**8-** O usuário também poderá retornar a página inicial do site **SouJunior**, clicando em **"Home"** no topo da Página;

**Seção 1 - Texto Sobre Área de Atuação -Back-end**

O desenvolvimento back-end é a criação e manutenção da parte "não visível" de uma aplicação, que geralmente consiste na lógica de negócios, banco de dados, servidores e infraestrutura que permitem que o programa funcione corretamente. É o que sustenta o programa ou aplicativo e fornece dados e funcionalidades para a interface do usuário.
Os desenvolvedores back-end geralmente trabalham com linguagens de programação como Java, Python, Ruby e JavaScript, além de frameworks como Node.js, Django, Flask, Ruby on Rails, entre outros. Eles também usam bancos de dados relacionais e não relacionais, como MySQL, PostgreSQL, MongoDB, Redis e Cassandra, para armazenar e gerenciar dados.

Dentro da SouJunior os desenvolvedores juniores de Back-end tem a função de implementar e manter as tecnologias necessárias para garantir a eficiência dos sistemas, com auxilio dos mentores e Head. Além disso, é fundamental que haja uma boa integração entre outras áreas, como a de Produto, UX & UI design e Front-end, para garantir a melhor experiencia possível para o cliente final.

**Seção 2 - [Entrevista com a Head da Área de Produtos -  Wanderson Santos]**

Wanderson Santos é um desenvolvedor Back-end casado e pai de dois filhos, que fez sua transição de carreira no início do ano passado. Ele gosta de participar de projetos desafiadores, onde pode contribuir para solucionar problemas, e não tem medo de encarar algo novo. Especializado em NodeJs, ele possui experiência em sistemas Linux e Windows, além de habilidades em versionamento com Git e documentação de software com Swagger, Postman e Insomnia.

Além disso, também tem conhecimentos em Typescript com express, Nestjs e tem familiaridade com bancos de dados não-relacionais, como Mongo DB e relacionais como MySql e Postgres.

É uma pessoa comunicativa e flexível, com forte gerenciamento de tempo e capacidade de trabalhar em equipe. Sempre motivado e comprometido em aprender e lidar com novas ferramentas de trabalho para continuar aprimorando suas habilidades.

**1. Como você iniciou na área da tecnologia?**

Eu trabalhava e estudava ao mesmo tempo, acordava muito cedo 4h da manhã, e ficava estudando até a meia-noite, esse ponto fez com que eu aprendesse um pouco mais devagar. ainda mais por está em processo de migração de carreira, foi Bastante difícil e complicado, pois, não sabia o que estudar então consumia um pouco de tudo, até pegar firme no roadmap do Back-end.

**2. O que te motivou a fazer parte da SouJunior?** 

Gosto de projetos Open source e de aprender, então na SouJunior eu consegui encontrar essas duas coisas.

**3. Como você garante a colaboração e comunicação efetiva com as equipes envolvidas no desenvolvimento?**  

Temos reuniões com as equipes para alinhamentos, o servidor evoluiu muito e a comunicação melhorou bastante, pois, cada equipe tem uma pessoa responsável por ela, assim podemos ter uma melhor colaboração.

**4. O que mais entusiasma você no desenvolvimento?** 

Entender que estamos resolvendo os problemas das pessoas, e isso é extremamente gratificante, nada melhor do que construir algo e ver alguém usando.

**5. Como faz para se comunicar de forma eficaz com os membros da equipe Sou Junior?** 

Tento entender a dificuldade de cada um e separar as demandas para que todos possam colaborar e poder aprender.
Fazemos call para alinhamentos, reuniões para "pair programming" e temos um servidor para ajudar os juniores no que eles precisarem. Porém a comunicação principal permanece o nosso canal na SouJunior.

**6. Dentro das linguagens de programação qual você considera a mais importante e porque?** 

Cada uma tem suas qualidades, porém Javascript pode abrir um leque maior de opções, pois, com ele você pode ir para mobile, front-end e back-end.

**7. Qual Soft Skills você considera fundamental para um desenvolvedor back-end?** 

Saber expressar suas dúvidas, não segurar problemas/impedimentos, buscar sempre tentar resolver, não conseguiu peça ajuda. Pois, impedimentos podem atrasar as entregas, além disso uma boa comunicação com o time é essencial.

**8. Dica para algum juninho de como entrar no mercado?** 

Extraia de cada entrevista um aprendizado, tudo o que é perguntado é o que você precisa aprender, fiz assim, quando me perguntavam algo que eu não sabia, depois da entrevista corria para aprender.

**Head**

**Wanderson Santos**
![Wanderson Santos](https://github.com/SouJunior/site-soujunior/assets/81826043/f75053e5-8277-44ce-bb3b-1a63770958b7)
- **LinkedIn:** https://www.linkedin.com/in/wandersongsantos/
- **Discord:**: 427653385123135490

**Mentores**

**Edcleidson Júnior**

![Image](https://github.com/SouJunior/site-soujunior/assets/31568030/70677ec4-cd75-4639-a2bc-6f3a234301ed)

**LinkedIn:**  https://www.linkedin.com/in/eddiescj/
**Discord**: 856534558229266461

**ThiagoRCode**
(falta foto)
**LinkedIn:**  
**Discord**: 277391239912095745

**Juniores**

**Bruna Oliveira**
![Bruna Oliveira](https://avatars.githubusercontent.com/u/102394235?v=4)
**LinkedIn:**  https://www.linkedin.com/in/bruoliveiraalves/
**Discord**: 966470010191118337

**Igor Gonçalves**
![Image](https://github.com/SouJunior/site-soujunior/assets/31568030/e150151e-6bae-492c-8e6d-9163963c8df2)
**LinkedIn:** https://www.linkedin.com/in/igords-goncalves/
**Discord**: 889953880576774204

**João Lucas Bugati**
![João Lucas Bugati](https://avatars.githubusercontent.com/u/102599241?v=4)
**LinkedIn:**  https://www.linkedin.com/in/jo%C3%A3o-lucas-bugati-591009236/
**Discord**: 442345207342825472

**Patrick da Rocha Otero**
![Patrick da Rocha Otero](https://avatars.githubusercontent.com/u/83041269?v=4)
**LinkedIn:**  https://www.linkedin.com/in/patrick-da-rocha-otero/
**Discord**: 487789753916456981

**Ytallo Cesar**
![Ytallo Cesar](https://github.com/SouJunior/site-soujunior/assets/81826043/a3721978-99b7-4e95-903d-e5c2971390d7)
**LinkedIn:**  https://www.linkedin.com/in/ytallocesar/
**Discord**: 457845559609262081

**Comment by andyarauj0** [comment]
@RntSaturnino como anda a entrevista? precisa de ajuda?

**Comment by andyarauj0** [comment]
@RntSaturnino acho que você pegou bem os feedbacks das outras na hora de construir essa US.

Só alguns pontos de dúvida: 

Na seção 1, quando vc traz uma visão da área,  "O desenvolvimento backend é a criação e manutenção da parte "não visível" de um aplicativo" você foca muito no lance do aplicativo, e é para além disso. Um site, como o nosso, por exemplo, precisa de um. Acho que vale dar só uma organizada nessas informações. Segue um artigo da alura que pode te ajudar nisso : https://www.alura.com.br/artigos/o-que-e-front-end-e-back-end

Além disso, ao longo do texto, falamos em back-end e backend. Acho que podemos dar uma padronizada né? O que acha?

De resto, fiz minhas considerações pela entrevista no grupo. Como são respostas curtíssimas e sem muita profundidade, pensei em juntar as perguntas e respostas da 4 e da 6 (elas falam sobre comunicação) e cortaria a pergunta 3. O que acha?

**Comment by andyarauj0** [comment]
ok @RntSaturnino ! pode seguir para o quadro do Ready e organizá-lo de acordo com a prioridade ;)

**Comment by sabrinamir** [comment]
@brcaua poderia validar?

**Comment by sabrinamir** [comment]
@brcaua poderia validar?
