### ISSUE TITLE
Página de Cadastro para pessoas juniores

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-webapp#122]
**Definição**

**Como** usuário,
**Gostaria** de demonstrar interesse em ser Junior na Sou Junior, 
**Tendo** acesso a mais informações sobre como participar dos projetos.
___________________________________________________________________________________________________________

**Descrição**

Para que o usuário interessado em se tornar júnior será necessário realizar uma inscrição pelo site, na aba "Sou Junior".

___________________________________________________________________________________________________________

**Protótipos**

https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/SITE---Sou-Junior?page-id=3994%3A318&type=design&node-id=4042-161&viewport=433%2C623%2C0.14&t=S4BiiyoJJ13SSMw3-1&scaling=min-zoom&mode=design

![Image](https://github.com/SouJunior/site-soujunior/assets/146049420/36af4c68-3749-4aac-b8ff-d26343c92f2d)

___________________________________________________________________________________________________________

**Critérios de Aceite**

**1-** O usuário entrará no site da **SouJunior;**

**2-** O usuário irá clicar em "**Faça parte**" e ser direcionado para a seção "**Faça você também parte da nossa comunidade!**";

**3-** Ao clicar na seção **" Sou Junior "**, o usuário terá acesso à descrição da seção;

**4-** Ao clicar no botão "**Quero Participar**" o usuário será redirecionado para outra página, para fazer sua inscrição;

**5-** Na página de inscrição o usuário deverá preencher os dados manualmente;

**6-** O usuário deverá informar seu nome completo;
O campo "Nome completo" deverá ter capacidade para 100 caracteres.
*Campo obrigatório

**7-** O campo "**telefone**" deve ser preenchido manualmente e obrigatoriamente;

**8-** Caso o campo "**Telefone/Whatsapp**" possua um (DDD) inválido ou uma sequência ilógica, como "**0000-1111**" deve ser apresentada a seguinte mensagem ao usuário: “**Telefone Inválido**  abaixo do campo.

**9-** O campo "E-mail" deve ser preenchido manualmente; Para ser considerado um e-mail válido o mesmo dever conter o símbolo de @ + o domínio do e-mail + .com/.net/.br;
*Campo obrigatório

**10-** Caso o e-mail não siga os critérios de validação, então o sistema deverá apresentar uma mensagem abaixo do campo com a descrição: E-mail inválido.;

**11-** O campo "Confirmação de e-mail" deve ser preenchido manualmente e obrigatoriamente;
*Campo obrigatório

**12-** Caso os campos de e-mail e confirmação estejam divergentes, deverá ser apresentada a mensagem "E-mail Divergente" abaixo do campo;

**13-**  O campo **"LinkedIn"** deve ser preenchido manualmente sendo obrigatório. 

**14-** O campo "**Quanto tempo você tem disponível para atuar na Sou Junior**" teve conter um **Radiobutton list** com 4 opções, onde o usuário poderá escolher apenas uma das 4 opções:

- Até 5 horas semanais 
- 5 e 10 horas semanais
- 10 a 15 horas semanais 
- mais de 15 horas semanais 

**15-** Para garantir que o usuário faça uma escolha entre as quatro opções disponíveis, será necessário selecionar obrigatoriamente uma delas. Caso o usuário não selecione nenhuma opção, quando clicar em enviar um aviso será exibido abaixo do campo, solicitando que ele assinale uma das opções para prosseguir. **"Por favor assinale umas das opções pra prosseguir"**

**16-** O campo "Qual das opções abaixo, seria sua área de atuação/interesse ?" deverá ser preenchido através do drop-down (lista), Na parte escrito "selecione" terá uma seta no campo inferior a direita apontando para baixo.

**17-** Caso o usuário clique na seta uma lista em **dropdown** será apresentada contendo as seguintes opções:
Agilista
Scrum Mater
APM - Produto
Back-End
Data
Business
Designer de UI/UX
DevOps
Front-End
Marketing
Mobile
Quality Assurance (QA)
Tech Recruiter
*Campo obrigatório

**18-**Caso o usuário não escolha nem uma das opções ao clica em enviar, ele receberá o seguinte aviso em Pop-up **"Para seguir com o envio, escolha uma das opções".**

**19-**. Um campo com caixa de texto de 1500 (Mil e quinhentos) caracteres será inserido para que o usuário possa descrever "Pode me contar um pouco sobre o motivo que o levou a escolher essa área de atuação?"

**20-.** Um contador de caracteres será mostrado no campo superior a direita da caixa de texto para o usuário.

**21-**Caso o Usuário ultrapasse o limite de caracteres o mesmo não conseguira digitar e o contador de caracteres ficará em vermelho.

**22-** Caso os campos obrigatórios não forem preenchidos, ao clicar em "**Enviar**"  aparecerá uma mensagem em vermelho no campo não preenchido "**o campo não foi preenchido**";

**23-** Após o último campo terá um botão: "**Enviar**" 

**24-** O usuário deverá ter acesso ao botão "**Enviar **" para enviar os dados preenchidos;

**25-** Quando o usuário clicar em "Enviar", aparecerá uma pop-up com a mensagem "**Dados enviados com sucesso, logo nossa equipe entrará em contato com você**"

**26-** Os dados do usuário deverão ser direcionados para o e-mail do  "**Brandão**"; [wouerner@soujunior.tech]

**27-** O usuário será redirecionado para a "home" após clicar em "**Enviar**";

**28-** Após clicar em "**Voltar**" ou qualquer lugar que atualize a página, aparecerá um pop-up com um botão escrito "**Você deseja mesmo cancelar a inscrição?" com a opção "sim" e "não"**;

**29-** Caso o cliente opte por "**sim**" ele será redirecionado para a "**home**";

**30-** Caso o cliente opte por "**não**" os dados continuarão preenchidos e ele deverá clicar em "**Enviar**" para enviar a inscrição.

___________________________________________________________________________________________________________

**Informações Adicionais**
Qualquer observação importante para melhorar o entendimento da User Story
___________________________________________________________________________________________________________

**DoR - Definition of Ready**
- [ ] O design/wireframe foi definido e aprovado.

- [ ] A tarefa foi priorizada de acordo com o backlog e com as necessidades.

- [ ]  Os critérios de aceite estão claramente definidos a serem executada pela equipe.

- [ ] As dependências do projeto foram identificadas e resolvidas e documentadas.

- [ ] A equipe entendeu e concordou com as definições de "pronto" para a tarefa.
___________________________________________________________________________________________________________

**DoD - Definition of Done**
- [ ] Todos os requisitos funcionais definidos foram implementados e testados.

- [ ] O site está em conformidade com as especificações.

- [ ] O site é responsivo e funciona em diferentes tamanhos de tela e dispositivos.

- [ ] O site é acessível para usuários com deficiência.

- [ ] O tempo de carregamento da página é aceitável.

- [ ] O código foi testado por meio de testes automatizados.

- [ ] Os testes de aceitação do usuário foram realizados com sucesso.

- [ ] O design do site está de acordo com as diretrizes definidas.

- [ ] O site é esteticamente atraente e fácil de usar.

- [ ] A documentação do código é completa e atualizada.

- [ ] A documentação do usuário está disponível e é fácil de usar.

- [ ] O site foi implantado com sucesso no ambiente de produção.

- [ ] As configurações do servidor foram realizadas conforme as especificações definidas pelo cliente.

**Comment by RntSaturnino** [comment]
@andyarauj0 07/06 @

**Comment by sabrinamir** [comment]
@hygorvaz você pode validar?

**Comment by hygorvaz** [comment]
> @hygorvaz você pode validar?

@sabrinamir nao compreendi a numero 32. Ademais, o restante é bem padrão do que já foi consolidado até o momento. Pode seguir.

**Comment by sabrinamir** [comment]
@hygorvaz você pode validar?

**Comment by hygorvaz** [comment]
Ótimo @sabrinamir . Podemos seguir

**Comment by sabrinamir** [comment]
@brcaua e @JoaoPauloAmendolaDev  poderia validar?

**Comment by JoaoPauloAmendolaDev** [comment]
validado

**Comment by sabrinamir** [comment]
@brcaua  poderia validar?
