### ISSUE TITLE
Propósito, Missão, Visão e Valores

### ISSUE THREAD

**Issue by savannes** [SouJunior/site-webapp#124]
________________________________________________________________________________________________

**Definição**

**Como** usuário, 
**Necessito** de ter acesso a Propósito, Visão, Missão e Valores da SouJunior
**Para** que eu possa conhecer melhor a empresa

**Descrição**

Para que o usuário do site da SouJunior possa conhecer melhor a empresa através da Propósito, Missão, Visão e Valores (https://github.com/SouJunior/site-soujunior/issues/124) uma página de PVMV será introduzida ao site.

_________________________________________________________________________________________________________

**Protótipos**

https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/SITE---Sou-Junior?page-id=4189%3A420&type=design&node-id=4191-801&viewport=163%2C359%2C0.12&t=QM0WOUcNwtquY4pw-1&scaling=min-zoom&starting-point-node-id=4191%3A801&mode=design

![Image](https://github.com/SouJunior/site-soujunior/assets/31568030/3cd68c56-2449-411a-8c7f-ea921298f9d2)
__________________________________________________________________________________________________________

**Critérios de Aceite**

**1.** O usuário entrará no site da SouJunior, clicará em "Sobre Nós", que abrirá um sub menu e  poderá acessar a página de "Propósito, Missão, Visão e Valores” na _Navbar_ e no menu do rodapé;

**2.** O site deve ter uma página dedicada para a Propósito, Missão, Visão e Valores;

**3.** Ao clicar no Botão "Propósito, Missão, Visão e Valores " a página será atualizada para "Propósito, Missão, Visão e Valores";

**4.** No campo da página o seguinte texto deverá aparecer.

**Propósito** — porque fazemos o que fazemos:

Impactar na formação de uma nova geração _tech_ pela forma de pensar e agir.

**Missão** — o que buscamos todos os dias:

Conectar potenciais às oportunidades para transformar a realidade das pessoas e das empresas. 

**Visão**— qual o nosso foco:

Ser a maior incubadora de talentos _tech_ nacional, tornando-se referência na formação dos Juninhos e Juninhas através de seu laboratório de experiência, com a construção de uma mentalidade de aprendizagem, colaboração, produtividade e assertividade.

***Em **Valores**, ocorrerá uma transição automática de 20 segundos entre cada slide, destacando todos os Valores da SouJunior***

**Valores** — somos JUNIORES e esses são os nossos pilares:

* Juniores só no nome: temos a mentalidade de sempre ir além e entregar mais.
   - Realizamos entregas de impacto, com responsabilidade e excelência;
   - Nos comportamos com uma postura ativa e madura para com os problemas, não somente os resolvemos como também os solucionamos;

* Universal para todos, prezamos pela diversidade e inclusão porque acreditamos que a oportunidade deve ser para todas as pessoas.
   - Buscamos a pluralidade de ideias, pontos de vista e origens;
   - Tratamos com respeito e acolhimento todas as pessoas envolvidas;

* Narrabilidade no que diz respeito à nossa postura de protagonistas em escrever a própria história.
    - Agimos como protagonistas de nossas carreiras no dia a dia;

* Interatividade, porque sabemos como a comunicação é uma ferramenta poderosa a ser aperfeiçoada e que a sua principal utilidade é gerar ação.
   - Interagimos de maneira engajada com as ações da SouJunior e para com a própria comunidade;
    - Gostamos de ajudar as pessoas e também de sermos ajudados;

* Obstinação com o nosso futuro, pois sabemos que a vida de um Juninho exige persistência e resiliência.
   - Somos pessoas dedicadas, disciplinadas e buscamos um aprendizado contínuo;
   - Temos nossos objetivos de vida e carreira, então sabemos como o SouJunior pode nos ajudar e vice-versa;
   - Diante das adversidades, sempre nos lembramos do que nos move;

* Responsabilidade com o projeto, com as nossas ações e com a nossa própria marca pessoal e profissional.
   - Sabemos lidar bem com prazos, acordos e demandas;
   - Entendemos o que representa um processo de voluntariado e o que o SouJunior representa;

* Exemplo, agimos para buscar trazer o melhor nas pessoas através das nossas conexões.
   - Sabemos que o exemplo arrasta, então agimos como exemplos positivos e agregadores dentro do SouJunior;

* Sinergia nas ações que constroem o SouJunior, somos cooperativos e agimos todos juntos em uma só direção.
   - Buscamos o alinhamento contínuo sobre o ecossistema do SouJunior;
   - Trabalhamos com uma comunicação assertiva, respeitosa, alinhada e consistente entre times e pessoas;
   - Temos a comunicação assíncrona por padrão porque o nosso comportamento permite isso;
___________________________________________________________________________________________________________

**Informações Adicionais**
Qualquer observação importante para melhorar o entendimento da User Story
___________________________________________________________________________________________________________

**DoR - Definition of Ready**
- [ ] O design/wireframe foi definido e aprovado.

- [ ] A tarefa foi priorizada de acordo com o backlog e com as necessidades.

- [ ]  Os critérios de aceite estão claramente definidos a serem executada pela equipe.

- [ ] As dependências do projeto foram identificadas e resolvidas e documentadas.

- [ ] A equipe entendeu e concordou com as definições de "pronto" para a tarefa.
___________________________________________________________________________________________________________

**DoD - Definition of Done**
- [ ] Todos os requisitos funcionais definidos foram implementados e testados.

- [ ] O site está em conformidade com as especificações.

- [ ] O site é responsivo e funciona em diferentes tamanhos de tela e dispositivos.

- [ ] O site é acessível para usuários com deficiência.

- [ ] O tempo de carregamento da página é aceitável.

- [ ] O código foi testado por meio de testes automatizados.

- [ ] Os testes de aceitação do usuário foram realizados com sucesso.

- [ ] O design do site está de acordo com as diretrizes definidas.

- [ ] O site é esteticamente atraente e fácil de usar.

- [ ] A documentação do código é completa e atualizada.

- [ ] A documentação do usuário está disponível e é fácil de usar.

- [ ] O site foi implantado com sucesso no ambiente de produção.

- [ ] As configurações do servidor foram realizadas conforme as especificações definidas pelo cliente.

**Comment by TayTeixeira** [comment]
@hygorvaz , Você pode validar os critérios de aceite e a UI de baixa fidelidade por favor? Assim que validado, prosseguiremos com a UI de alta fidelidade!
Me avise se necessitar de alguma alteração! 
Obrigada!

**Comment by TayTeixeira** [comment]
@hygorvaz , você pode validar essa US por favor?

**Comment by hygorvaz** [comment]
> @hygorvaz , você pode validar essa US por favor?

Aprovado!
