### ISSUE TITLE
[Home/ Nossas Iniciativas] Verificar a complexidade de tornar aleatório os slides a cada entrada

### ISSUE THREAD

**Issue by lairareis** [SouJunior/site-webapp#160]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/products/issues/55

- **DESCRIÇÃO DO BUG:** Com a retirada da transição automática seria interessante ter outra maneira de transição dos slides.

- **EVIDÊNCIA:** 

![Image](https://user-images.githubusercontent.com/98753928/246956792-4660c526-a2dd-4a01-9032-d16c34b57a6c.png)

Modelo para verificação do tempo:
https://www.figma.com/file/XoZ6GKJ854Zxb0OvqNTlEh/SITE---Sou-Junior?type=design&node-id=799-2970&mode=design&t=22RB5mssWCUzI8lz-0

- SOLUÇÃO:  Transição aleatória a cada entrada na página, com um temporizador de 20 segundos para mudar o card.

**Comment by lairareis** [comment]
@Vanessapcs

**Comment by anikape** [comment]
@lairareis @Vanessapcs eu sugiro um tempo maior para transição automática. Podemos testar algo entre 15/30 segundos. Inicialmente havia sido pedido 7 segundos, o que de fato ficava muito rápido e impossibilitando a leitura.

**Comment by sabrinamir** [comment]
@hygorvaz, você poderia validar?
Testamos com 20 segundos e ficou bom de ler os dois cards de apresentação.

**Comment by hygorvaz** [comment]
> @hygorvaz, você poderia validar?
> Testamos com 20 segundos e ficou bom de ler os dois cards de apresentação.

Aprovado!

**Comment by sabrinamir** [comment]
@brcaua  poderia validar?

**Comment by brcaua** [comment]
@sabrinamir isso já foi desenvolvido e mergeado no site, certo?

**Comment by sabrinamir** [comment]
@brcaua não é pra ter subido ainda pois não validamos o ponto
