### ISSUE TITLE
Alteração de Link - Card Site

### ISSUE THREAD

**Issue by sabrinamir** [SouJunior/site-webapp#199]
LINK DA US DE REFERÊNCIA: https://github.com/SouJunior/products/issues/55

DESCRIÇÃO DA ALTERAÇÃO: Solicitado pelo Brandão a alteração de link do site.
De: https://discord.com/channels/759176734460346423/1009798805459304540
Para: https://bit.ly/soujunior-labs

EVIDÊNCIA:

![Image](https://github.com/SouJunior/site-soujunior/assets/146049420/47c28cc9-c998-4dcb-983d-e673503c0448)

SOLUÇÃO: Por favor, atualize os links nos cards que exibem as iniciativas da SouJunior, substituindo-os pelo novo link gerado pelo encurtador de links.
De: https://discord.com/channels/759176734460346423/1009798805459304540
Para: https://bit.ly/soujunior-labs

**Comment by sabrinamir** [comment]
@hygorvaz você pode validar a US?
O Brandão pediu para fazer esta alteração.

**Comment by hygorvaz** [comment]
Aprovado

**Comment by sabrinamir** [comment]
@brcaua poderia validar?

**Comment by sabrinamir** [comment]
@brcaua poderia validar?

**Comment by sabrinamir** [comment]
@hiagomu pode implementar a alteração?
