### ISSUE TITLE
Quem Somos (HOME)

### ISSUE THREAD

**Issue by HerikPavan** [SouJunior/site-webapp#2]
![Image](https://user-images.githubusercontent.com/112632457/188452717-c1aa8b4b-b76b-4de5-b04a-0ba3e5d1bdd5.png)

**Comment by EstelaMizukawa** [comment]
Finalizado o texto para a primeira página do site "O que é o SouJunior?"
[O que é o SouJunior?.pdf](https://github.com/SouJunior/Site/files/9538082/O.que.e.o.SouJunior.pdf)
