### ISSUE TITLE
Reestruturação do formulário para Mentores

### ISSUE THREAD

**Issue by sabrinamir** [SouJunior/site-webapp#235]
**name**: Reestruturação do Formulário para Mentores - Site
**about**: User Story do Produto "Site".
**title**: "[Reestruturação do Formulário para Mentores - Site]"
**labels**: ''
**assignees**: ''
____________________________________________________________________________
**Definição**

Como candidato, desejo me inscrever no formulário de processo seletivo para Mentores da SouJunior, para que possa competir por uma vaga e ajudar no desenvolvimento dos juniores, para que se sintam preparados para o mercado de trabalho e consigam seu "Sim" nas vagas.
_____________________________________________________________________________

**Descrição**

Esta User Story aborda a necessidade de duas squads da SouJunior, a do Site e a do Backoffice RH, que estão colaborando para reestruturar o formulário para Mentores. O objetivo é satisfazer as necessidades do RH da SouJunior, que precisa de dados para realizar um ranqueamento eficiente dos novos candidatos. Como parte dessa iniciativa, também será desenvolvida uma página com a identidade visual da SouJunior. Nessa primeira etapa, a V1, estamos focando na reestruturação do formulário.
____________________________________________________________________________
Protótipos
https://www.figma.com/proto/tB2QJPPRgojSvLf2Y4gGBX/Formul%C3%A1rio-SouJunior?node-id=293-3349&t=S5cxS2GXdVLRizV5-1
____________________________________________________________________________

**Critérios de aceite**

-O usuário entrará no site da SouJunior.

-O usuário irá clicar em "Faça parte" e será direcionado para a seção "Faça você também parte da nossa comunidade!".

-Ao clicar na seção "Sou Mentor", o usuário terá acesso à descrição da seção.

-Ao clicar no botão "Quero Participar", o usuário será redirecionado para outra página para fazer sua inscrição.

-O usuário deverá informar o nome completo.
Campo obrigatório

-O usuário deverá informar o e-mail e confirmar o e-mail no campo abaixo.
Para ser considerado um e-mail válido, ele deve conter o símbolo de @ + o domínio do e-mail + .com/.net/.br.
Campo obrigatório
Caso o e-mail não siga os critérios de validação, o sistema deverá apresentar uma mensagem abaixo do campo com a descrição: "E-mail inválido."

-O usuário deve preencher o campo LinkedIn.
Campo obrigatório

-O campo "A SouJunior realiza reuniões e atividades no período noturno. Você tem disponibilidade para atuar nesse turno?˜, deve escolher apenas uma opção.
Campo obrigatório
( ) Sim
( ) Não

-O campo "Considerando a participação mínima de 5 horas semanais para o projeto. Quanto tempo você poderia dedicar por semana ao voluntariado?" deve ser de múltipla escolha. Ele terá 4 opções, onde o usuário poderá escolher apenas uma:
Campo obrigatório
( ) 5 horas
( ) 5 a 10 horas
( ) 10 a 15 horas
( ) Mais de 15 horas
Caso o usuário não selecione nenhuma opção no campo "Quanto tempo você poderia dedicar por semana ao voluntariado?", quando clicar em "Enviar", um aviso será exibido abaixo do campo, solicitando que ele assinale uma das opções para prosseguir: "Por favor, assinale uma das opções para prosseguir."

-O campo "Qual a sua disponibilidade para início?" deve ser de múltipla escolha. Ele terá 3 opções, onde o usuário poderá escolher apenas uma e a 3ª opção será aberta caso nenhuma das outras opções responda à situação do usuário:
Campo obrigatório
( ) Imediato
( ) Em até 1 mês
( ) Em uma data específica: ___________

-O campo "Qual das opções abaixo seria sua área de interesse?˜, terá as áreas de atuação da SouJunior, onde o usuário só poderá escolher uma opção.
Campo obrigatório
[Áreas de Atuação]
( ) Produto
( ) Design
( ) Agilidade
( ) Back-End
( ) Front-End
( ) Dados
( ) QA - Quality Assurance
( ) DevOps
( ) Tech Recruitment
( ) Business

-Caso o usuário não selecione nenhuma opção no campo "Qual das opções abaixo seria sua área de interesse?", quando clicar em "Enviar", um aviso será exibido abaixo do campo, solicitando que ele assinale uma das opções para prosseguir: "Por favor, assinale uma das opções para prosseguir."

-Ainda no campo "Qual das opções abaixo seria sua área de interesse?", se o usuário escolher a área de Produto, deverá aparecer opções de subáreas de Produto para o usuário selecionar apenas uma.
Campo obrigatório
[Áreas de Produto]
( ) Product Growth
( ) Product OPS
( ) Product Marketing Manager
( ) Social Media
( ) APM - Associate Product Manager

-Ainda no campo "Qual das opções abaixo seria sua área de interesse?", se o usuário escolher a área de Design, deverá aparecer opções de subáreas de Produto para o usuário selecionar apenas uma.
Campo obrigatório
[Áreas de Design]
( ) UX/UI
( ) Design Ops

-O campo "Há quanto tempo você atua no mercado de trabalho?" deve escolher apenas uma opção.
Campo obrigatório
( ) 6 meses a 1 ano
( ) 1 a 3 anos
( ) 3 a 5 anos
( ) Mais de 5 anos

-No campo "Compartilhe um pouco mais sobre sua experiência no mercado.", o candidato deve responder uma pergunta aberta.
O campo aceitará de 250 a 500 caracteres.
Campo obrigatório
Caso os campos obrigatórios não forem preenchidos, ao clicar em "Enviar", aparecerá uma mensagem em vermelho no campo não preenchido: "O campo não foi preenchido."

-No campo "Você já possui experiência anterior sobre mentoria?", o candidato deve responder uma pergunta aberta.
O campo aceitará de 250 a 500 caracteres.
Campo obrigatório
Caso os campos obrigatórios não forem preenchidos, ao clicar em "Enviar", aparecerá uma mensagem em vermelho no campo não preenchido: "O campo não foi preenchido."

-No campo "Antes de finalizarmos sua candidatura, há algum aspecto importante sobre sua motivação para se tornar voluntário na SouJunior?", o candidato deve responder uma pergunta aberta.
O campo aceitará de 250 a 500 caracteres.
Campo obrigatório
Caso os campos obrigatórios não forem preenchidos, ao clicar em "Enviar", aparecerá uma mensagem em vermelho no campo não preenchido: "O campo não foi preenchido."

-Ao término das perguntas, deverá ser incluído 2 checkboxs para a confirmação de termos e condições e também de autorização de uso de dados, conforme [US](https://github.com/SouJunior/site-backend/issues/10)

-Após o último campo, terá um botão: "Enviar", que só será ativado quando o usuário preencher todos os campos e aceitar os termos e condições. (O texto dos termos e condições será definido em uma outra US).

-Quando o usuário clicar em "Enviar", aparecerá um pop-up com a mensagem: "Inscrição concluída. Você receberá um e-mail de confirmação em breve.", e logo em seguida, será enviado um e-mail de confirmação da inscrição. (O texto do e-mail será definido em uma outra US).

-Os dados do usuário deverão ser direcionados para uma planilha que será gerenciada pela Squad de Backoffice.

-O usuário será redirecionado para a "home" após clicar em "Enviar".

-Após clicar em "Voltar" ou em qualquer lugar que atualize a página, aparecerá um pop-up com um botão escrito: "Você deseja mesmo cancelar a inscrição?" com a opção "sim" e "não".

-Caso o usuário opte por "sim", ele será redirecionado para a "home".

-Caso o usuário opte por "não", os dados continuarão preenchidos e ele deverá clicar em "Enviar" para enviar a inscrição.

____________________________________________________________________________
DoR - Definition of Ready

- [ ]  O design/wireframe foi definido e aprovado.

- [ ]  A tarefa foi priorizada de acordo com o backlog e com as necessidades.

- [ ]  Os critérios de aceite estão claramente definidos a serem executada pela equipe.

- [ ]  As dependências do projeto foram identificadas e resolvidas e documentadas.

- [ ]  A equipe entendeu e concordou com as definições de "pronto" para a tarefa.

____________________________________________________________________________
DoD - Definition of Done

- [ ]  Todos os requisitos funcionais definidos foram implementados e testados.

- [ ]  O site está em conformidade com as especificações.

- [ ]  O site é responsivo e funciona em diferentes tamanhos de tela e dispositivos.

- [ ]  O site é acessível para usuários com deficiência.

- [ ]  O tempo de carregamento da página é aceitável.

- [ ]  O código foi testado por meio de testes automatizados.

- [ ]  Os testes de aceitação do usuário foram realizados com sucesso.

- [ ]  O design do site está de acordo com as diretrizes definidas.

- [ ]  O site é esteticamente atraente e fácil de usar.

- [ ]  A documentação do código é completa e atualizada.

- [ ]  A documentação do usuário está disponível e é fácil de usar.

- [ ]  O site foi implantado com sucesso no ambiente de produção.

- [ ]  As configurações do servidor foram realizadas conforme as especificações definidas pelo cliente.

**Comment by sabrinamir** [comment]
@IsabellaMaciel pode validar?

**Comment by IsabellaMaciel** [comment]
Sim e alinhado contigo agora hehe

**Comment by sabrinamir** [comment]
Processo arquivado devido a alteração para que Backoffice crie o formulário de uma forma diferente.
