### ISSUE TITLE
Criação do Formulário para Heads

### ISSUE THREAD

**Issue by sabrinamir** [SouJunior/site-webapp#237]
**name**: Criação do Formulário para Heads
**about**: User Story do Produto "Site".
**title**: "[Criação do Formulário para Heads]"
labels: ''
assignees: ''
____________________________________________________________________________
**Definição**

Como candidato, desejo me inscrever no formulário de processo seletivo para Heads da SouJunior, para que possa competir por uma vaga e ajudar na estruturação da área.
_____________________________________________________________________________
**Descrição**

Esta User Story aborda a necessidade de duas squads da SouJunior, a do Site e a do Backoffice RH, que estão colaborando para reestruturar o formulário para Heads. O objetivo é satisfazer as necessidades do RH da SouJunior, que precisa de dados para realizar um ranqueamento eficiente dos novos candidatos. Como parte dessa iniciativa, também será desenvolvida uma página com a identidade visual da SouJunior. Nessa primeira etapa, a V1, estamos focando na criação do formulário.
____________________________________________________________________________
**Protótipos**
Aguardando UX/UI produzir
____________________________________________________________________________
**Critérios de aceite**

- O usuário entrará no site da SouJunior.

- O usuário irá clicar em "Faça parte" e será direcionado para a seção "Faça você também parte da nossa comunidade!".

- Ao clicar na seção "Sou Head", o usuário terá acesso à descrição da seção.

- Ao clicar no botão "Quero Participar", o usuário será redirecionado para outra página para fazer sua inscrição.

- No alto da página estará descrito "Quero ser Head", e abaixo o texto explicativo:
"Para se candidatar como Head preencha as informações abaixo. Nosso time entrará em contato para te conhecer um pouco mais e entender de que forma você poderá contribuir com os projetos e iniciativas da SouJunior.

- O usuário deverá informar o nome completo.
Campo obrigatório

- O usuário deverá informar o e-mail e confirmar o e-mail no campo abaixo.
Para ser considerado um e-mail válido, ele deve conter o símbolo de @ + o domínio do e-mail + .com/.net/.br.
Campo obrigatório
Caso o e-mail não siga os critérios de validação, o sistema deverá apresentar uma mensagem abaixo do campo com a descrição: "E-mail inválido."

- O usuário deve preencher o campo LinkedIn.
Campo obrigatório

- O campo "A SouJunior realiza reuniões e atividades no período noturno. Você tem disponibilidade para atuar nesse turno?˜, deve escolher apenas uma opção.
Campo obrigatório
( ) Sim
( ) Não

- O campo "Quanto tempo por semana você poderia se dedicar ao voluntariado?" deve ser de múltipla escolha. Ele terá 4 opções, onde o usuário poderá escolher apenas uma:
Campo obrigatório
( ) Até 5 horas
( ) 5 a 10 horas
( ) 10 a 15 horas
( ) Mais de 15 horas
Caso o usuário não selecione nenhuma opção no campo "Quanto tempo você poderia dedicar por semana ao voluntariado?", quando clicar em "Enviar", um aviso será exibido abaixo do campo, solicitando que ele assinale uma das opções para prosseguir: "Por favor, assinale uma das opções para prosseguir."

- O campo "Qual a sua disponibilidade para início?" deve ser de múltipla escolha. Ele terá 3 opções, onde o usuário poderá escolher apenas uma e a 3ª opção será aberta caso nenhuma das outras opções responda à situação do usuário:
Campo obrigatório
( ) Imediato
( ) Outro: ___________

- O campo "Qual das opções abaixo seria sua área de interesse?˜, terá as áreas de atuação da SouJunior, onde o usuário só poderá escolher uma opção.
Campo obrigatório
[Áreas de Atuação]
( ) Agilidade
( ) Back-End
( ) Business
( ) Dados
( ) Design
( ) DevOps
( ) Front-End
( ) Produto
( ) QA - Quality Assurance
( ) Tech Recruitment
( ) Outro: ___________
Caso o usuário não selecione nenhuma opção no campo "Qual das opções abaixo seria sua área de interesse?", quando clicar em "Enviar", um aviso será exibido abaixo do campo, solicitando que ele assinale uma das opções para prosseguir: "Por favor, assinale uma das opções para prosseguir."

- O campo "Há quanto tempo você atua no mercado de trabalho?" deve ser de múltipla escolha. Ele terá 4 opções, onde o usuário poderá escolher apenas uma:
Campo obrigatório
( )  1 ano
( )  1 a 3 anos
( )  4 a 6 anos
( )  Acima de 6 anos
Caso o usuário não selecione nenhuma opção no campo "Há quanto tempo você atua no mercado de trabalho?", quando clicar em "Enviar", um aviso será exibido abaixo do campo, solicitando que ele assinale uma das opções para prosseguir: "Por favor, assinale uma das opções para prosseguir."

- No campo "Qual é a sua motivação para se tornar um Head no SouJunior?", o candidato deve responder uma pergunta aberta.
Campo obrigatório
Caso os campos obrigatórios não forem preenchidos, ao clicar em "Enviar", aparecerá uma mensagem em vermelho no campo não preenchido: "O campo não foi preenchido."

- No campo "Já atuou em papel de liderança e/ou mentoria? Conte um pouco mais sobre a experiência.", o candidato deve responder uma pergunta aberta.
Campo obrigatório
Caso os campos obrigatórios não forem preenchidos, ao clicar em "Enviar", aparecerá uma mensagem em vermelho no campo não preenchido: "O campo não foi preenchido."

- No campo "Já disseminou conhecimento de alguma maneira (podcast, sala de aula, palestras, congressos)?Caso sim, quais?", o candidato deve responder uma pergunta aberta.
Campo obrigatório
Caso os campos obrigatórios não forem preenchidos, ao clicar em "Enviar", aparecerá uma mensagem em vermelho no campo não preenchido: "O campo não foi preenchido."

- No campo "Se conecta com a função de estruturar estrategicamente a área de sua expertise em conjunto com outros heads, formando times e focando no crescimento da sua disciplina no Ecossistema SouJunior?", o candidato deve responder uma pergunta aberta.
Campo obrigatório
Caso os campos obrigatórios não forem preenchidos, ao clicar em "Enviar", aparecerá uma mensagem em vermelho no campo não preenchido: "O campo não foi preenchido."

- No campo "Compartilhe um pouco mais sobre sua experiência no mercado.", o candidato deve responder uma pergunta aberta.
Campo obrigatório
Caso os campos obrigatórios não forem preenchidos, ao clicar em "Enviar", aparecerá uma mensagem em vermelho no campo não preenchido: "O campo não foi preenchido."

- Após o último campo, terá um botão: "Enviar", que só será ativado quando o usuário preencher todos os campos e aceitar os termos e condições. (O texto dos termos e condições será definido em uma outra US).

- Quando o usuário clicar em "Enviar", aparecerá um pop-up com a mensagem: "Inscrição concluída. Você receberá um e-mail de confirmação em breve.", e logo em seguida, será enviado um e-mail de confirmação da inscrição. (O texto do e-mail será definido em uma outra US).

- Os dados do usuário deverão ser direcionados para uma planilha que será gerenciada pela Squad de Backoffice.

- O usuário será redirecionado para a "home" após clicar em "Enviar".

- Após clicar em "Voltar" ou em qualquer lugar que atualize a página, aparecerá um pop-up com um botão escrito: "Você deseja mesmo cancelar a inscrição?" com a opção "sim" e "não".

- Caso o usuário opte por "sim", ele será redirecionado para a "home".

- Caso o usuário opte por "não", os dados continuarão preenchidos e ele deverá clicar em "Enviar" para enviar a inscrição.

____________________________________________________________________________
**DoR - Definition of Ready**
- [ ] O design/wireframe foi definido e aprovado.
- [ ] A tarefa foi priorizada de acordo com o backlog e com as necessidades.
- [ ]  Os critérios de aceite estão claramente definidos a serem executada pela equipe.
- [ ] As dependências do projeto foram identificadas e resolvidas e documentadas.
- [ ] A equipe entendeu e concordou com as definições de "pronto" para a tarefa.
___________________________________________________________________________________________________________

**DoD - Definition of Done**
- [ ] Todos os requisitos funcionais definidos foram implementados e testados.
- [ ] O site está em conformidade com as especificações.
- [ ] O site é responsivo e funciona em diferentes tamanhos de tela e dispositivos.
- [ ] O site é acessível para usuários com deficiência.
- [ ] O tempo de carregamento da página é aceitável.
- [ ] O código foi testado por meio de testes automatizados.
- [ ] Os testes de aceitação do usuário foram realizados com sucesso.
- [ ] O design do site está de acordo com as diretrizes definidas.
- [ ] O site é esteticamente atraente e fácil de usar.
- [ ] A documentação do código é completa e atualizada.
- [ ] A documentação do usuário está disponível e é fácil de usar.
- [ ] O site foi implantado com sucesso no ambiente de produção.
- [ ] As configurações do servidor foram realizadas conforme as especificações definidas pelo cliente.

**Comment by IsabellaMaciel** [comment]
@sabrinamir Corrigir período

**Comment by sabrinamir** [comment]
Processo arquivado devido a alteração para que Backoffice crie o formulário de uma forma diferente.
