### ISSUE TITLE
Correção de Link no Botão

### ISSUE THREAD

**Issue by sabrinamir** [SouJunior/site-webapp#254]
LINK DA US DE REFERÊNCIA: (https://github.com/SouJunior/site-webapp/issues/117)

DESCRIÇÃO DO BUG: No botão 'Quero Participar!' da seção 'Faça Parte', o redirecionamento para o formulário de inscrição só funciona ao clicar no texto 'Quero Participar', em vez de funcionar ao clicar em qualquer parte do botão.

EVIDÊNCIA:
 ![Image](https://github.com/user-attachments/assets/cd60e891-f8b6-4c5e-84d3-d4b53c2e9bd6)

SOLUÇÃO: Ajustar a área de clique do botão "Quero Participar!" para que o redirecionamento funcione ao clicar em qualquer parte do botão, e não apenas no texto.

**Comment by IsabellaMaciel** [comment]
@sabrinamir aprovado

**Comment by IsabellaMaciel** [comment]
@TayTeixeira aprovado

**Comment by CryslaineGomes** [comment]
Cenarios de testes:
[Cenarios - Link botão #254.pdf](https://github.com/user-attachments/files/17177138/Cenarios.-.Link.botao.254.pdf)
Evidencias:

**Comment by IsaacMeneguini** [comment]
Evidencia.-.Link.botao.254.mp4"
