### ISSUE TITLE
Retirada de X

### ISSUE THREAD

**Issue by sabrinamir** [SouJunior/site-webapp#255]
LINK DA US DE REFERÊNCIA: https://github.com/SouJunior/site-soujunior/issues/117

DESCRIÇÃO: No rodapé da página, o ícone da rede social X ainda consta.

EVIDÊNCIA:

![Image](https://github.com/user-attachments/assets/e6e5cfc2-13c9-45c8-8bac-49db4714fe8d)

SOLUÇÃO: Deverá ser retirado para do rodapé, permanecendo apenas as demais redes sociais oficiais da sou junior. Deixar 4 redes sociais por linha para ficar mais organizado e alinhado.

**Comment by IsabellaMaciel** [comment]
@sabrinamir Oi, sugiro acrescentar que fiquem 4 redes sociais por linha

**Comment by CryslaineGomes** [comment]
Cenarios de teste e evidencias:
[Cenarios e evidências - Retirada de X #255.pdf](https://github.com/user-attachments/files/17177127/Cenarios.e.evidencias.-.Retirada.de.X.255.pdf)
