### ISSUE TITLE
Como participar do projeto

### ISSUE THREAD

**Issue by HerikPavan** [SouJunior/site-webapp#4]

**Comment by EstelaMizukawa** [comment]
Texto "Quem pode participar" está quase pronto.
Preciso verificar apenas alguns pontos sobre mentores com Herik/Brandão

![Image](https://user-images.githubusercontent.com/112426449/189767804-ef640416-0c9e-4808-89fb-83ed9a69b6d2.png)

**Comment by EstelaMizukawa** [comment]
Formulário de pessoas interessadas.
https://www.figma.com/file/mzZecSDjEp8KeQkn7ucKVE/Figjam-Sou-Junior?node-id=0%3A1


![Image](https://user-images.githubusercontent.com/112426449/189776600-6eca1b1a-60f1-438f-997d-c4f741591aec.png)

**Comment by EstelaMizukawa** [comment]
Finalizadas as perguntas e campos do formulário para interessados em participar.

https://www.figma.com/file/mzZecSDjEp8KeQkn7ucKVE/Figjam-Sou-Junior?node-id=0%3A1



![Image](https://user-images.githubusercontent.com/112426449/190228546-07a9feed-2cb7-4746-87a7-1a5e50830fe0.png)

**Comment by thaygjo** [comment]
UserFlow do site, se tiverem algum apontamento a ser alterado só avisar.

https://miro.com/app/board/uXjVPWH9Hl8=/?share_link_id=614605406952

![Image](https://user-images.githubusercontent.com/86688624/191116183-3047cd64-8361-411c-9c9f-647c13a40e27.jpg)

**Comment by EstelaMizukawa** [comment]
Texto para o site - Atualizado hoje

https://www.figma.com/file/mzZecSDjEp8KeQkn7ucKVE/Figjam-Sou-Junior?node-id=0%3A1


![Image](https://user-images.githubusercontent.com/112426449/191835394-1db0bb88-d26d-46b9-8847-4d0ca8948c42.png)

**Comment by thaygjo** [comment]
UserFlow do site atualizado

https://miro.com/app/board/uXjVPWH9Hl8=/?share_link_id=614605406952



![Image](https://user-images.githubusercontent.com/86688624/192156246-ac0c650b-33bc-4af8-ad84-3233b06801d3.png)
