### ISSUE TITLE
Áreas de Atuação - Produtos

### ISSUE THREAD

**Issue by andyarauj0** [SouJunior/site-webapp#96]
**História de usuário - Áreas de Atuação - Produto**

**Definição**

**Como** usuário eu 
**Gostaria** de acessar o site 
**Para** conhecer mais sobre a Área de Produtos

**Descrição:**
Este documento tem como objetivo apresentar aos usuários como atua a Área de Produtos e uma entrevista com a head, Vanêssa.

**Protótipo**

![Image](https://user-images.githubusercontent.com/124841403/224133223-bf5407f4-0f84-4071-85b8-8dee40cd242d.png)

https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/SITE---Sou-Junior?page-id=753%3A2880&type=design&node-id=3181-15644&viewport=1503%2C823%2C0.24&t=F48KtIT61ks0MYHA-1&scaling=min-zoom

**Critérios de aceite**

**1.** Para acesso a **"Área de Atuação"** o usuário deverá **acessar a Home do site da SouJunior**.

**2.** Após acessar o site da SouJunior, o usuário deverá descer a barra de rolagem até a **"Área de atuação"** e selecionar acategoria **"Produtos"**.

![Image](https://user-images.githubusercontent.com/124841403/224133418-61257526-ab58-4488-b3d4-0f0f3f115826.png)

**3.** Após selecionar a opção **"Produtos"**. O usuário Visualizará um breve contexto sobre a Área de Produtos e logo em seguida a entrevista com o Head da Área, **Vanêssa Santana**.

**4.** Antes da entrevista, **deverá constar a foto da Head de Produtos - Vanêssa Santana e as suas Redes Sociais:**
- **LinkedIn:** https://www.linkedin.com/in/vanessa-patricia/
- **Discord:** Vanêssa Santana#3595

**5.** No final da entrevista deverá constar a foto da equipe de Produtos da SouJunior, em ordem alfabética, junto com o LinkedIn e Discord. 

**6.** Ao clicar no botão do Linkedin ou do Discord, o usuário será direcionado para uma nova página em outra aba, para que o Usuário possa continuar navegando no Site caso desejado.

**7.** Para o usuário retornar a página inicial (home) do site SouJunior, deverá selecionar o botão de retroceder da página.[Image](https://user-images.githubusercontent.com/124841403/224133840-56e6551b-4d26-4de4-a810-f7fdbb252e1b.png)

**Seção 1 - [Texto Sobre Área de Atuação - Produtos]**

A área Produtos dentro da SouJunior tem como objetivo assegurar que a tecnologia desenvolvida atenda às necessidades e expectativas dos clientes. 
Isso envolve a estratégia de Produtos, a avaliação de viabilidade técnica e financeira, a liderança do desenvolvimento e a entrega de soluções de alta qualidade.
O objetivo da equipe de Produtos é garantir que o software Open source SouJunior, seja desenvolvido de forma colaborativa e atenda às necessidades e expectativas da comunidade de usuários. 
Além disso, a Equipe de Produtos também interage com todas as áreas da SouJunior, para garantir a adoção e o sucesso do produto no mercado.

**Seção 2 - [Entrevista com a Head da Área de Produtos - Vanêssa Santana]**

A nossa Head de Produtos é a Vanêssa Santana, nascida em Recife mas residente em São Paulo.
Formada em Sistemas de Informação e pós graduada em Gerenciamento de Projetos e Gerenciamento de Produtos.
Atua na área da TI há 17 anos, assumindo papéis de Gerente de Projetos, Head de Produtos e Agile Coach. Atualmente trabalha com o Agile Project Manager na Bayer.
Engajada na comunidade tecnológica, ela mentora pessoas em transição de carreira, ministra cursos voltados para a agilidade e atua como trainee da Certificadora PeopleCert, preparando os interessados para as provas de certificações do universo Ágil. Também foi co-autora do livro “Jornada Ágil do Produto” e participa como escritora líder de mais quatro livros da “Jornada Colaborativa”, onde também faz parte da equipe de curadores do livro “Ágil além da TI”
Na SouJunior ela ocupa o cargo de Head de Produtos e lidera uma equipe entre mentores e juninhos, para a construção de 6 produtos, além de apoiar a comunidade da SouJunior Lab, selecionando e orientando os PMs e Agilistas juniores na condução de suas atividades.
Porém, como não só de TI vive o ser humano, nas horas vagas (que todos nós queremos saber quais são), ela gosta de viajar para conhecer novos lugares e culturas, ler, escrever livros sobre temas não relacionados à tecnologia, assistir filmes, conversar com os seus amigos e mimar suas sobrinhas.
Confira a seguir a entrevista que a equipe de produtos do site SouJunior fez com a Vanêssa Santana, para conhecer um pouco mais sobre sua jornada profissional e opinião a respeito da área que atua:

1.**Como você iniciou na área da tecnologia?**

Sempre gostei de tecnologia e de cálculo. Acompanhando a trajetória do trabalho de meu pai, ingressei no curso de Engenharia Química, onde fiz parte de um grupo que estudava uma linguagem de programação chamada Fortran. Fui conhecendo e me apaixonei por desenvolvimento de software, quando resolvi prestar outro vestibular para tecnologia, do qual fui aprovada e mudei de curso. Desde então segui uma trajetória voltadas para projetos, iniciando na análise de negócios com a análise da qualidade, depois líder de projetos, gerente de projetos e, com o surgimento da agilidade, tive oportunidade de trabalhar como Head de Produtos e Agile Coach, mas atualmente sou Agile Project Manager.  

2. **O que te motivou a fazer parte da SouJunior?**

Ensinar pessoas, disseminar conhecimento e trabalhar em iniciativas de capacitação sempre foi o meu intuito e por isso participo de algumas comunidades como Mulheres de Produtos, Mulheres Agilistas, Mentora e tento ajudar as pessoas na sua evolução profissional.
Durante algumas visitas ao LinkedIn, comecei a ver bastante postagens da SouJunior e achei a proposta bem bacana. Pesquisando um pouco mais, notei que eles ainda não tinham a área do Produtos, então chamei o Brandão para conversar, fiz uma proposta de inclusão de APMs no movimento, ele gostou da ideia e desde então atuo como Head de área, onde tive a oportunidade de estruturá-la e vê-la crescer cada vez mais.

3.**Como você acompanha e mensura o sucesso do produto?**

O critério de sucesso do Produto depende muito de cada organização. Portanto, após conheccer e avaliar o contexto organizacional, podermos criar as nossas métricas, que vai de uma massa estratégica de dados até um bate papo com os Usuários, para que possamos garantir que o produto represente o que a organização acredita que é sucesso.

4. **Como você envolve sua equipe no processo de desenvolvimento de produtos?**

Procuro envolver a equipe em todo as fases do processo de desenvolvimento do produto. Em alguns casos eu tenho uma conversa anterior com o sponsor/stakeholder para avaliarmos alguns pontos e verificarmos uma viabilidade de construção ou prioridade de início, mas após isso a equipe já é informada que temos um grande trabalho pela frente.
Nós analisamos em conjunto, definimos atividades de discovery que serão executadas, trabalhamos na ideação, desenho, acompanhamento da construção e entrega de valor, onde os APMs tenham a capacidade de aprender e participar de maneira prática em todas as fases desse processo.

5. **Como você lida com o equilíbrio entre adicionar novas funcionalidades e manter a simplicidade e facilidade de uso do produto?**

Essas duas questões estão muito alinhadas e descreve basicamente o nosso trabalho como profissional de produtos. Constantemente precisamos verificar se o nosso produto necessita de novas funcionalidades, sejam provenientes da dor do usuário ou falta de engajamento destes, onde temos que entender o motivo e propor soluções estratégicas e até criativas para o problema encontrado, mas ao mesmo tempo temos que fazer com que essa jornada do usuário dentro do produto seja fluida, fácil, intuitiva e simples, pois tudo que é complexo para ser executado pode causar frustração, fazendo com que a possibilidade de abandono seja alta e que o nosso esforço não gere valor.
Em síntese, para que possamos ter o equilíbrio dessas duas frentes, incrementar o produto e mantê-lo simples, é fundamental conhecermos o nosso Usuário e sabermos o que ele precisa. Para isso, além de sabermos priorizar e definir o que é mais importante naquele momento, também devemos trabalhar com outros profissionais do time, como por exemplo UX Resercher e UI, que podem nos auxiliar a termos um olhar mais próximo do nosso cliente final e construirmos algo especialmente para ele.

6. **Sabemos que a área de TI está em constante inovação. Portanto, como você acredita que as pessoas podem se manter atualizadas para essas novas oportunidades que surgem e mudanças que ocorrem diariamente nesse universo tecnológico?**

Temos que ter consciência que na área de TI tudo mudará, pois é um universo onde sempre estamos atualizando, transformando, deletando ideias e recomeçando.
Aconselho que você se atualize da maneira que conseguir, seja lendo livros, promovendo networking, conversando e conhecendo as pessoas e buscando cursos gratuitos. Costumo incentivar as pessoas a gastar menos, porque às vezes elas não podem, mas quando falamos de TI, não é porque algo é gratuito que não vai te ajudar fortemente na sua transição de carreira.  Evolui bastante nesses 17 anos de jornada profissional, mas só consegui fazer isso porque estava constantemente buscando me manter atualizada com as tendências do mercado, falando com pessoas, estudando e fazendo cursos (até os gratuitos). O que não podemos fazer é nos acomodarmos e acreditarmos que não temos mais nada a aprender.

7. **Como você garante a colaboração e comunicação efetiva com as equipes envolvidas no desenvolvimento do produto?**

Podemos ser os maiores e melhores promotores de engajamento, colaboração, vontade de participação das pessoas, mas mesmo assim não garantimos que tenhamos uma comunicação efetiva, pois isso também depende de cada uma delas. Mas, para driblar esse desafio e tornar as pessoas mais envolvidas, falando especificamente da SouJunior, sempre tento promover a transparência, mostrando o que estamos fazendo. Além disso, tentamos reunir ao máximo com as pessoas, buscar a opinião e solicitar a participação delas, para que elas se sintam pertencentes aquela construção, além de promover um ambiente seguro e de espaço aberto ao diálogo.

8. **. Como você resolve conflitos de interesses entre equipes de produto e outras áreas?**

Estamos lidando com pessoas e cada uma tem um conceito de valor diferente, onde o que uma pode ver algo como empecilho, outra pode ver como um ganho ou um bônus.
Acho que não é só sobre resolver conflitos, mas como poder mitigá-los. Então, muitas vezes, se antecipar aos conflitos vem muito sobre você explicar o valor da área de produtos para as outras áreas, equalizando o entendimento de que estamos ali para contribuir. 
Trazendo esse conceito para a SouJunior, promovemos uma live onde eu e o Brandão falamos um pouco sobre a área de Produtos e como ela poderia servir positivamente as outroas áreas de uma organização, além de dar voz ao Usuário e favorecer também a empresa através de uma entrega de valor. Com isso disso acredito que as pessoas conseguiram compreender porque estamos querendo saber de tudo e até se envolver em todos os processos que estejam associados a construção do nosso incremento, evitando alguns problemas de comunicação ou conflitos entre as pessoas.

9. **Como você garante que o produto atenda às necessidades e expectativas dos usuários e clientes?**

Uma das maiores responsabilidades do produto é entregar valor,maximizar o seu valor, tendo em vista que ele é sempre feito para sanar uma dor e atender a uma necessidade.
Como podemos garantir que o que estou entregando realmente atenderá as necessidades e expectativas do meu usuário? É preciso conhecê-los, entendê-los e ouvi-los. Se nosso produto é global ou nacional não temos como alcançar a todos, por isso a importância de se trabalhar bem com pesquisa. Sendo assim, não adianta simplesmente tentar adivinhar o que o seu cliente deseja para poder lançar um produto, você tem que realmente saber o que ele deseja. Existem várias ferramentas que facilitam esse jornada, mas sem dúvidas os dados ajudam bastante nesse processo de ver onde o cliente está, onde ele desiste e abandona a jornada no nosso produto. A partir disso vamos atrás para fazer entrevistas e entender o motivo deles desistirem. 
Com essas informações é possível que possamos entregar sempre algo que não só atenda ou supere as expectativas no nosso Uusário.

![Image](https://user-images.githubusercontent.com/91374502/221251471-30a7c74b-4f96-48db-af2d-f3189e343b65.png)
**Vanêssa Santana - Head de Produtos**

**Seção 3 - [ Foto Equipe de APM's da SouJunior]**

**MENTORES:**

**Marcelo Bizarro**
![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/8c785c18-481c-4ef5-be23-bf1269d1b018)
- LinkedIn: https://www.linkedin.com/in/marcelobiza/
- Discord: marcelobiza#8780

Adriano Laurino

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/db04f1e1-28c6-4000-923a-cffe53d72a39)
**Adriano Laurino**
- LinkedIn: https://www.linkedin.com/in/adrianolaurindo/
- Discord: adrianolaurindo

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/204ca85c-3533-4c36-a421-4a45c7f7f73f)
**Fábio Escanfella**
- LinkedIn: https://www.linkedin.com/in/fabioescanfella/
- Discord: Fábio Dalbon Escanfella#1884

![Image](https://user-images.githubusercontent.com/91374502/221251751-f90507d6-f797-4bfb-abca-743d5f6ffecb.jpeg)
**- Leonardo Honório**
- LinkedIn: https://www.linkedin.com/in/leonardo-hon%C3%B3rio/
- Discord: Leonardo Honório#7055

![Image](https://user-images.githubusercontent.com/91374502/226066675-65f135db-eef3-4e91-afec-bdf2ebf4d848.png)
**- Tainá Wandelli**
- LinkedIn: https://www.linkedin.com/in/tain%C3%A1-wandelli-26aba864/
- Discord: Tainá Wandelli#7486

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/c1d3f5e1-c0a5-4e38-841a-2bb08205142c)
**Ramis Oliveira**
- LinkedIn: https://www.linkedin.com/in/ramis-oliveira/
- Discord: Ramis_kjl#3600

**JUNINHOS**

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/3fa52211-affe-4898-9550-8d3e7d9839fc)
Leticia Oliveira
- LinkedIn: https://www.linkedin.com/in/oliveira-leticia/
- Discord: LeticiaOliveira0802

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/49194bb5-8bac-499c-a45b-8303af867a41)
**Marjorie Lebelein**
- LinkedIn: https://www.linkedin.com/in/marjorie-lebelein/
- Discord: MarjorieLebelein#7582

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/9f51af8d-56cf-4f70-9b64-e15c6344ac45)
**Alana Dias**
- LinkedIn: https://www.linkedin.com/in/alana-dias/
- Discord: alanagarbuli#9141

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/41c737d6-3899-4295-9386-34bd5325c2fa)
**Lúcio Flávio Magalhães**
- LinkedIn: https://www.linkedin.com/in/lucio-flavio-magalhaes/
- Discord: luciofnobrega

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/fbcc6ca1-6069-47b2-b0f5-7ca0b3c9a0fd)
**Everton Antonio Pereira Bertolai**
- LinkedIn: https://www.linkedin.com/in/bertolai/
- Discord: evertchou

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/40db06b7-ed88-49d5-83e4-995b1cf6bb66)
**Laira Reis**
- LinkedIn: https://www.linkedin.com/in/lairareis/
- Discord: Laira#2417

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/7c7724e8-e65d-412c-8ce9-b8848ff045d1)
**Savanne Soares**
- LinkedIn: https://www.linkedin.com/in/savannesoares/
- Discord: Savanne Soares#5622

![Image](https://user-images.githubusercontent.com/91374502/221252515-1f4e1294-b2a1-46ae-be9f-2f6c23cadf7c.jpeg)
**- Akira Shimazu**
- LinkedIn: https://www.linkedin.com/in/akirashimazu/
- Discord: Akira Shimazu#4801

![Image](https://user-images.githubusercontent.com/91374502/226074179-2b83d175-d985-4843-b97c-d9060a178511.png)
**- Jacqueline Moura**
- LinkedIn: https://www.linkedin.com/in/jacqueline-moura/
- Discord: Jacqueline Moura#5148 

![Image](https://user-images.githubusercontent.com/91374502/221252516-1333a3f0-9202-4591-b19f-240afafc1100.jpeg)
**- Renato Saturnino**
- LinkedIn: https://www.linkedin.com/in/renato-saturninno/
- Discord: Renatosaturnino

![Image](https://user-images.githubusercontent.com/91374502/221252509-cec3e588-0c5f-4fcd-9993-721f1a7c12ff.jpg)
**- Talita Bitencourt**
- LinkedIn: https://www.linkedin.com/in/bitencourttalita/
- Discord: litabitencourt

![Image](https://user-images.githubusercontent.com/91374502/221252518-dbe5d3ee-247c-4851-ad74-cb8d4890a066.png)
**- Tatiane Alves**
- LinkedIn: https://www.linkedin.com/in/sevlast/
- Discord: Tatiane Alves (sevlast)#6761

![Image](https://user-images.githubusercontent.com/91374502/221252517-5f2590dc-3083-4eb4-ac3d-7c9df6750050.png)
**- Thiago Silva**
- LinkedIn: https://www.linkedin.com/in/thiagosansi/
- Discord: thiagosansi4449

![Image](https://user-images.githubusercontent.com/91374502/227714643-3bb7543b-0bc4-452f-9b71-82796b6618a2.jpeg)
**- Jamir Salim**
- LinkedIn: https://www.linkedin.com/in/jamirnsalim/
- Discord: Jamirnsalim

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/704f9fcb-0cfa-4205-a461-0bc6d6832351)
Camila Rocha
- LinkedIn: https://www.linkedin.com/in/camila-rocha8/
- Discord: Camilarocha1

![Image](https://user-images.githubusercontent.com/124841403/230916883-497edba2-750c-4b94-8841-768254f12dfa.png)
**- Luiz Neves**
- LinkedIn: https://www.linkedin.com/in/luizguilhermefranca/
- Discord: Luiz Guilherme França#4397

![Image](https://user-images.githubusercontent.com/124841403/230917104-ee23ba5c-b800-482f-b9cd-62ac80430dd0.png)
**- Michel Alves**
- LinkedIn: https://www.linkedin.com/in/michelralves/
- Discord: Michelalves

![Image](https://user-images.githubusercontent.com/124841403/230917183-5d9baba3-d1e4-452e-a4c0-4329dee72221.png)
**- Steffany Martins**
- LinkedIn: https://www.linkedin.com/in/steffany-temoteo-martins/
- Discord: steffany.martins#4448

**[INSPIRAÇÃO PARA UX]**

![Image](https://user-images.githubusercontent.com/124841403/224025226-ed73e11f-68b4-4341-a358-6ffa62a646c8.png)

![Image](https://user-images.githubusercontent.com/124841403/224025265-864aca3c-0c2a-4995-b304-c6e5b754ccec.png)

**Comment by andyarauj0** [comment]
@Leacyntra10 quando você consegue finalizar essa US? consegue sinalizar pra gente? Há algum impeditivo, para que eu possa te ajudar?

**Comment by EduBeserra** [comment]
teste

**Comment by andyarauj0** [comment]
@Samueldiasp ou @RntSaturnino algum dos dois conseguem fazer o protótipo para a área de produtos? Como é o primeiro na lista de prioridades, seria legal ter

**Comment by Samueldiasp** [comment]
Pode deixar, @andyarauj0! Vou atualizar esta US.

**Comment by Samueldiasp** [comment]
@andyarauj0 Atualizei a US com o Protótipo e Critérios de Aceite.

Aproveitei também para atualizar os links do LinkedIn e Discord da Equipe.

**Comment by andyarauj0** [comment]
show de bola, @Samueldiasp !!! US revisada.

**Comment by EduBeserra** [comment]
Boa noite! as areas dos mentores e dos juninhos não estão descritas na US

**Comment by EduBeserra** [comment]
Entendido! segue o link do prototipo inicial 

https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/FAQ-Sou-Junior?page-id=753%3A2880&node-id=753-2881&viewport=337%2C948%2C0.28&scaling=scale-down-width

**Comment by Vanessapcs** [comment]
@EduBeserra inclui a Tainá (mentoraa) e a Jacqueline (APM) que não estavam na lista.

**Comment by EduBeserra** [comment]
Alterações feitas

**Comment by EduBeserra** [comment]
Boa noite segue uma nova versão do protótipo com uma alternativa ao topo sem o uso do desenho usado na home:

https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/FAQ-Sou-Junior?page-id=753%3A2880&node-id=809-3723&viewport=678%2C665%2C0.23&scaling=scale-down-width

**Comment by Vanessapcs** [comment]
@EduBeserra adicionar os seguintes juninhos na foto de equipe. Obrigada!!



![Image](https://user-images.githubusercontent.com/91374502/227714643-3bb7543b-0bc4-452f-9b71-82796b6618a2.jpeg)

- **Jamir Salim**

LinkedIn: https://www.linkedin.com/in/jamirnsalim/
Discord: Jamir N Salim#2071



![Image](https://user-images.githubusercontent.com/91374502/227714743-46394aa6-eb4c-41ed-b793-6c2a8ed81c2e.jpeg)

- **Letícia Lima**

LinkedIn: https://www.linkedin.com/in/let%C3%ADcia-higino-neri-lima-271662208/
Discord: Letícia Lima#6366



![Image](https://user-images.githubusercontent.com/91374502/227714799-13f24813-8828-474c-b636-ce53a8e45c8a.jpeg)

- **Luiz Neves**

LinkedIn: https://www.linkedin.com/in/luizguilhermefranca/
Discord: 



![Image](https://user-images.githubusercontent.com/91374502/227714882-5bc92113-6db1-488e-817b-586a7bcbd27a.jpg)

- **Michel Alves**

LinkedIn: https://www.linkedin.com/in/michelralves/
Discord: Michel Alves#6888



![Image](https://user-images.githubusercontent.com/91374502/227714942-f7be2c2a-5d13-4df0-a352-76a64dcecba7.jpeg)

- **Steffany Martins**

LinkedIn: https://www.linkedin.com/in/steffany-temoteo-martins/
Discord: Steffany Martins#4448

**Comment by sabrinamir** [comment]
@limaricardo @wandersonDeve esta US está parada. Poderiam validar?

**Comment by sabrinamir** [comment]
@brcaua e @wandersonDeve  poderiam validar a parte de frontend e backend para finalizarmos esta US?

**Comment by brcaua** [comment]
Revisado e aprovado.
