### ISSUE TITLE
Áreas de Atuação - Tech Recruiter

### ISSUE THREAD

**Issue by Samueldiasp** [SouJunior/site-webapp#98]
**Definição:**

**Como** usuário
**Gostaria** de acessar o site
**Para** conhecer mais sobre a Área de Tech Recruiter

**Descrição:**

Este documento tem como objetivo apresentar aos usuários como atua a Área de Tech Recruiter e uma entrevista com a head, Daniele Oliveira.

**Protótipo:**

https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/SITE---Sou-Junior?page-id=3965%3A3990&type=design&node-id=3965-3991&viewport=526%2C396%2C0.12&t=UhTh7ijsYh5ST9yb-1&scaling=min-zoom&starting-point-node-id=3965%3A3991&mode=design

![Image](https://user-images.githubusercontent.com/124841403/223172869-a17cf16f-ec22-4b46-91bd-07e2985484f1.png)

**Critérios de aceite:**

1. Para acesso a **"Área de Atuação"** o usuário deverá acessar a **Home do site da SouJunior**.

2. Após acessar o site da SouJunior, o usuário deverá descer a barra de rolagem até a **"Área de atuação"** e selecionar a categoria **"Tech Recruiter"**;

![Image](https://user-images.githubusercontent.com/124841403/223902715-3565c26e-0f4d-4d13-9279-0e162cee6a9a.png)

3. Após selecionar a opção **"Tech Recruiter"**, o usuário acessará a página da Área de Atuação. Visualizará um breve contexto sobre a Área de Tech Recruiter, uma breve biografia da Head da Área e logo em seguida a entrevista com a Head da Área, **Daniele Oliveira**;

4. Antes da entrevista, **deverá constar a foto da Head de Tech Recruiter e as suas Redes Sociais:**

- LinkedIn: https://www.linkedin.com/in/daniele-oliveirapsi/
- Discord: 781888047289466910

5. No final da entrevista deverá constar a foto da equipe de Tech Recruiter da SouJunior.

6. Ao clicar no botão do Linkedin ou do Discord, o usuário deverá ser informado de que ele será direcionado para uma nova página em outra aba, para que o Usuário possa continuar navegando no Site caso desejado.

7. Para o usuário retornar a página inicial do site SouJunior, deverá selecionar o botão de retroceder no inicio da página.![Image](https://user-images.githubusercontent.com/124841403/223902562-b0b2aece-d1b0-4615-be31-ef9b304f0f2d.png)

**Seção 1 - [Texto Sobre Área de Atuação - Tech Recruiter]**

A área de Tech Recruiter da SouJunior é responsável por encontrar e selecionar candidatos qualificados para posições dos Times. Os profissionais dessa área utilizam diversas técnicas para atrair talentos, como a criação de anúncios persuasivos e o uso de redes sociais. Além disso, eles são responsáveis por avaliar os currículos dos candidatos, conduzir entrevistas técnicas e analisar a compatibilidade dos candidatos com a cultura e os valores do Projeto.

Os profissionais desta área também desempenham um papel fundamental na construção da marca SouJunior, pois criam uma experiência positiva para os candidatos durante todo o processo de recrutamento e seleção. Além disso, a área de Tech Recruiter é altamente estratégica e exige profissionais que sejam proativos, flexíveis e capazes de se adaptar rapidamente às mudanças do mercado.

**Seção 2 - [Entrevista com a Head da Área de Tech Recruiter - Daniele Oliveira]**

A nossa Head de Tech Recruiter, Daniele Oliveira, é mãe, psicóloga, mulher preta e uma Nordestina apaixonada por experiências!
Trabalhando na área de Desenvolvimento de Pessoas e RH desde 2014 possui atuação em diversas frentes que envolvem Atração de talentos, Onboarding, Treinamento, Gestão da Cultura Organizacional, Desenvolvimento de Carreira, Jornada do colaborador e Offboarding.
Também tem algumas experiências em departamento pessoal, o que me acrescentaram conhecimentos
importantes sobre Legislação Trabalhista.
Considera a carreira como uma jornada não linear cheia de possibilidades e descobertas, portanto ama
construir legados e deixar um pedaço dela em tudo o que faz.

**1. Pode me falar um pouco sobre sua trajetória profissional e como você chegou ao cargo atual na SouJunior?**
Cheguei no cargo de mentora e em seguida assumi o papel de head do time de recrutamento

**2. Como você define o papel do Tech Recruiter em uma empresa de tecnologia?**
Seu principal papel é identificar, atrair, avaliar e selecionar candidatos qualificados para preencher
posições técnicas. Seu papel inclui colaborar com os líderes de tecnologia e gestores de contratação para
entender as necessidades da empresa, criar estratégias de recrutamento, conduzir entrevistas técnicas,
avaliar as habilidades dos candidatos e garantir que os candidatos escolhidos se alinhem com a cultura
da empresa.

**3. Quais são as principais habilidades que você considera essenciais para um Tech Recruiter de sucesso?**
Conhecimento técnico: Um entendimento sólido das tecnologias, linguagens de programação e
habilidades necessárias para as posições em aberto.
Compreensão da cultura da empresa: A capacidade de compreender a cultura e os valores da empresa
para encontrar candidatos que se encaixem bem.
Habilidades de comunicação: Boas habilidades de comunicação são essenciais para interagir com
candidatos e membros da equipe de tecnologia.
Habilidade de avaliação: A capacidade de avaliar as habilidades técnicas dos candidatos de forma eficaz.
Pensamento estratégico: Desenvolver estratégias de recrutamento eficazes para atender às
necessidades da empresa.
E o que considero mais importante, Foco em relacionamento: Construir relacionamentos sólidos com
candidatos, equipes de tecnologia e gestores de contratação

**4. Como você avalia as competências técnicas dos candidatos durante o processo de recrutamento e que atendam às exigências técnicas e culturais da empresa?**
Avaliar projetos anteriores, portfólios e trabalhos práticos. Além disso, é importante destacar que a
entrega técnica, o que eu sei fazer, é importante, mas como eu faço, como eu entrego a habilidade
técnica é ainda mais importante. É aí onde entra a comunicação, a negociação, a inteligência emocional.
Por isso, avaliar soft skills interessantes para o cargo também é uma estratégia para garantir que os
candidatos demonstram uma compreensão profunda das tecnologias e habilidades necessárias.

**5. Em sua opinião, qual é a melhor forma de atrair talentos para uma empresa de tecnologia?**
É importante desenvolver uma cultura de trabalho atraente, destacar os benefícios e vantagens que a
empresa oferece, usar plataformas de recrutamento e redes sociais para promover oportunidades de
emprego. Pensar em programas de indicação também contribui bastante.

**6. Como você promove a diversidade e inclusão no processo de recrutamento de uma empresa de tecnologia?**
Trabalhar diversidade sempre será um desafio, enquanto ainda possuímos uma estrutura social que
impacta diretamente nesse recorte no mercado de tecnologia. Por isso é importante estabelecer
conexão com programas, grupos e comunidades que formam essas pessoas para que o acesso às vagas
estejam mais próximos. Acredito que o trabalho de vagas afirmativas também deve ser feito, mas exige
um cuidado com a compreensão dos dados de mercado referente ao perfil dentro do recorte de
diversidade. Além disso, não é possível trabalhar processos seletivos inclusivos se não houver uma
cultura de inclusão na organização.

**7. Quais são as principais tendências e desafios que você enxerga no mercado de recrutamento de tecnologia nos próximos anos?**
A automação de recrutamento, a busca por candidatos remotos e globais, a crescente demanda por
habilidades em áreas como inteligência artificial e segurança cibernética, bem como a concorrência
acirrada por talentos. Além disso, a diversidade e inclusão continuarão a ser uma pauta importante no
recrutamento.

**8. Como você trabalha em conjunto com a área de tecnologia da empresa, visando garantir que as necessidades do negócio sejam atendidas por meio do recrutamento?**
É importante manter um relacionamento próximo com a equipe de tecnologia e líderes de negócios. Isso
envolve a comunicação regular para entender as prioridades de contratação, as metas de negócios e as
habilidades técnicas necessárias. Devemos atuar como um parceiro estratégico que atua como uma
ponte entre as equipes de tecnologia as necessidades do negócio e as mudanças do mercado.

**9. O que os juniores poderiam fazer no processo seletivo que os ajudariam a compensar a falta de experiência?**
Destacar projetos pessoais ou acadêmicos relevantes, Mostrar um histórico de aprendizado rápido e
adaptação a novas tecnologias. Participar de estágios, programas de mentoria, voluntariado ou
bootcamps. Destacar habilidades não técnicas, como comunicação e colaboração. Mostrar um forte
desejo de contribuir para a empresa e aprender com colegas mais experientes. Além disso, sempre
oriento que estudem e fortaleçam fundamentos, ter domínio da base é sempre muito importante. Caso
não tenha muitos projetos reais para mostrar, uma dica interessante seria, trabalhar em casos fictícios
utilizando sua stack principal, essa pode ser uma maneira criativa de preencher o seu repertório com
relação a aplicação prática.
Sobre o momento da entrevista, é fundamental organizar o histórico dessas experiências. Para isso,
indico também que organize seu pensamento e as experiências que deseja compartilhar destacando as
regras de negócio ou as ferramentas que já consegue utilizar. Manter atenção total às perguntas para
garantir que as respostas estejam alinhadas com o que foi perguntado, evitando respostas genéricas e
desorganizadas. E o que sempre ressalto, senioridade também tem muito a ver com soft skills, por isso o
trabalho de autoavaliação constante te ajudará a entender que pontos podem ser melhorados e
trabalhar nisso.

**FOTO DA HEAD:**

![dani](https://github.com/SouJunior/site-soujunior/assets/146049420/c23cd05f-680c-41e7-8a6b-03db6af0ac07)

**FOTOS DA EQUIPE:**

![Image](https://github.com/SouJunior/site-soujunior/assets/146049420/8e3cfa07-7b03-42ad-ae4e-4faf8d3a5c90)
- Caroline Coelho (Mentora);
- LinkedIn: https://www.linkedin.com/in/coelho-caroline/
- Discord: 1047157935509360791

![Image](https://user-images.githubusercontent.com/124841403/223892996-835723eb-9922-4970-adf8-d9ab82c1c205.png)
- Ana Macenaz (Recruiter);
- LinkedIn: https://www.linkedin.com/in/anapaulasantoz/
- Discord: 762408284065628170

![Image](https://github.com/SouJunior/site-soujunior/assets/146049420/69694ce5-00c4-4a1d-9696-4564b3420701)
- Isabele Freire (Recruiter);
- LinkedIn: https://www.linkedin.com/in/isabellefs-psi/
- Discord: 1083743439671275530

![Image](https://github.com/SouJunior/site-soujunior/assets/146049420/8a539bfe-144f-415e-b3cb-dd5925abdabf)
- Larissa Araujo (Recruiter);
- LinkedIn: https://www.linkedin.com/in/larissafaraujo/
- Discord: 98973005857718272

**[INSPIRAÇÃO PARA UX]**

![Image](https://user-images.githubusercontent.com/124841403/224025226-ed73e11f-68b4-4341-a358-6ffa62a646c8.png)

![Image](https://user-images.githubusercontent.com/124841403/224025265-864aca3c-0c2a-4995-b304-c6e5b754ccec.png)

**Comment by Samueldiasp** [comment]
@Vanessapcs @andyarauj0 

Oi, pessoal! Poderiam validar esta US? Obrigado!

**Comment by Samueldiasp** [comment]
Olá, @andyarauj0! Gostei muito das suas observações e já realizei as alterações! Obrigado!

**Comment by andyarauj0** [comment]
@Samueldiasp sobre a foto da camila cavani, a head ficou de enviar?

**Comment by Samueldiasp** [comment]
@andyarauj0 Olá, mestre! A head está me enviando todas as fotos da Equipe. Acredito que ainda hoje consigo atualizar a US com todas as fotos.

**Comment by Samueldiasp** [comment]
@andyarauj0 Boa noite, mestre! Já atualizei com todas as fotos da Equipe e Critérios de Aceite. Poderia verificar?

**Comment by andyarauj0** [comment]
outra coisinha @Samueldiasp , vamos solicitar o linkedin da galera tb pra colocar na tela?

**Comment by Samueldiasp** [comment]
@andyarauj0 Pronto, mestre! Atualizei a US com o LinkedIn e Discord da Equipe.

**Comment by andyarauj0** [comment]
Excelente! US finalizada

**Comment by TayTeixeira** [comment]
@hygorvaz , você pode validar a US por favor?

**Comment by sabrinamir** [comment]
@brcaua poderia validar?

**Comment by sabrinamir** [comment]
@brcaua poderia validar?
